# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: [push]
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      # - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@iamrunar'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy-to-vps:
    # needs: publish-gpr
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      # https://github.com/appleboy/ssh-action
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        # ssh-keygen -t rsa -b 4096 -m PEM -C "github-actions" -f './github-actions2_rsa' 
        # github-actions.pub paste to vps_host:~/.ssh/authorized_keys
        # secrets.VPS_PRIVATE_KEY = <content of github-actions>
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        # PM2 is a daemon process manager that will help you manage and keep your application online
        # https://pm2.keymetrics.io/docs/usage/quick-start/
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          mkdir -p ~/apps/bybit-best-otc-sellers-bot
          cd ~/apps/bybit-best-otc-sellers-bot

          echo //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN} > .npmrc
          echo @iamrunar:registry=https://npm.pkg.github.com/ >> .npmrc
          echo always-auth=true >> .npmrc
          
          npm i @iamrunar/bybit-best-otc-sellers-bot
          pm2 restart node_modules/@iamrunar/bybit-best-otc-sellers-bot
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB-NPM-PACKAGE-TOKEN}}

        # npm config set @iamrunar:registry https://npm.pkg.github.com/
        # npm config set //npm.pkg.github.com/:_authToken ${{secrets.GITHUB_TOKEN}}